

include("test_copy_kernel.jl")
include("test_domain.jl")
include("test_particle_group.jl")
include("test_pbc_apply.jl")
include("test_pbc_global_add.jl")
include("test_pbc_global_move.jl")
include("test_pbc_pos_to_rank.jl")
include("test_pbc_global_transfer.jl")
include("test_global_array.jl")
include("test_global_array_write.jl")
include("test_cell_data_direct_read.jl")
include("test_cell_data_direct_write.jl")
include("test_add_extra_particle_dat.jl")
include("test_cell_to_particle_map_construction.jl")
include("test_pair_dof_part_basic_read.jl")
include("test_pair_dof_part_basic_write.jl")
